import { Brain, CheckSquare, ThumbsUp, AlertTriangle, FileText, Star, Download } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { jsPDF } from 'jspdf';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';

interface AnalysisResultProps {
  result: {
    score: number;
    rejectionReasons: string[];
    fixes: string[];
    summary: string;
    isNotCV?: boolean;
    documentType?: string;
    wasForceAnalyzed?: boolean;
  };
  onForceAnalyze?: () => void;
  isLoading?: boolean;
}

const StarRating = ({ rating, max = 5 }: { rating: number; max?: number }) => {
  return (
    <div className="flex items-center gap-1">
      {Array.from({ length: max }).map((_, i) => (
        <Star
          key={i}
          className={`w-5 h-5 ${i < rating ? 'fill-warning text-warning' : 'text-muted-foreground/30'}`}
        />
      ))}
      <span className="text-muted-foreground ml-2">({rating}/{max})</span>
    </div>
  );
};

const AnalysisResult = ({ result, onForceAnalyze, isLoading }: AnalysisResultProps) => {
  const rating = Math.round(result.score / 20);

  const generatePDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - margin * 2;
    let y = 20;

    // Title
    doc.setFontSize(24);
    doc.setTextColor(124, 58, 237); // Primary purple
    doc.text('PortTheFolio', pageWidth / 2, y, { align: 'center' });
    y += 10;

    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text('AI Portfolio Analysis Report', pageWidth / 2, y, { align: 'center' });
    y += 15;

    // Score
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(`Rating: ${rating}/5 stars (Score: ${result.score}/100)`, margin, y);
    y += 15;

    // Overall Assessment
    doc.setFontSize(16);
    doc.setTextColor(20, 184, 166); // Secondary teal
    doc.text('Overall Assessment', margin, y);
    y += 8;

    doc.setFontSize(11);
    doc.setTextColor(60, 60, 60);
    const summaryLines = doc.splitTextToSize(result.summary, maxWidth);
    doc.text(summaryLines, margin, y);
    y += summaryLines.length * 6 + 10;

    // Key Strengths
    doc.setFontSize(16);
    doc.setTextColor(124, 58, 237); // Primary purple
    doc.text('Key Strengths', margin, y);
    y += 8;

    doc.setFontSize(11);
    doc.setTextColor(60, 60, 60);
    const strengths = result.fixes.length > 0
      ? result.fixes.slice(0, Math.ceil(result.fixes.length / 2))
      : ['Strong combination of technical and soft skills', 'Concrete examples of accomplishments', 'Practical projects demonstrating skills'];

    strengths.forEach((item) => {
      const lines = doc.splitTextToSize(`• ${item}`, maxWidth - 5);
      if (y + lines.length * 6 > 280) {
        doc.addPage();
        y = 20;
      }
      doc.text(lines, margin + 5, y);
      y += lines.length * 6 + 3;
    });
    y += 7;

    // Areas for Improvement
    if (y > 250) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(16);
    doc.setTextColor(245, 158, 11); // Warning amber
    doc.text('Key Areas for Improvement', margin, y);
    y += 8;

    doc.setFontSize(11);
    doc.setTextColor(60, 60, 60);
    result.rejectionReasons.forEach((reason) => {
      const lines = doc.splitTextToSize(`• ${reason}`, maxWidth - 5);
      if (y + lines.length * 6 > 280) {
        doc.addPage();
        y = 20;
      }
      doc.text(lines, margin + 5, y);
      y += lines.length * 6 + 3;
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `Generated by PortTheFolio • Page ${i} of ${pageCount}`,
        pageWidth / 2,
        290,
        { align: 'center' }
      );
    }

    doc.save('portfolio-analysis-report.pdf');
  };

  return (
    <div className="rounded-2xl border border-border bg-card p-8 shadow-sm animate-fade-in">
      {result.isNotCV ? (
        <div className="space-y-6">
          <div className="border-l-4 border-destructive bg-destructive/5 p-6 rounded-r-xl">
            <h2 className="flex items-center gap-3 text-2xl font-bold text-destructive">
              <AlertTriangle className="w-8 h-8" />
              Analysis Failed
            </h2>
            <p className="text-destructive font-medium mt-2 text-lg">
              ATS Score: 0/100
            </p>
          </div>

          <div className="space-y-4">
            {result.documentType && (
              <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg bg-muted text-muted-foreground text-sm font-medium border border-border">
                <FileText className="w-4 h-4" />
                Detected Type: <span className="text-foreground">{result.documentType}</span>
              </div>
            )}

            <div className="p-4 bg-muted/30 rounded-xl border border-border">
              <h3 className="font-semibold mb-2 text-foreground">Why was this rejected?</h3>
              <p className="text-muted-foreground leading-relaxed">{result.summary}</p>
            </div>

            <p className="text-sm text-muted-foreground italic">
              * This system strictly analyzes Resumes, CVs, and Portfolios. Other documents are rejected to ensure quality analysis.
            </p>

            {onForceAnalyze && (
              <Button
                variant="outline"
                onClick={onForceAnalyze}
                disabled={isLoading}
                className="gap-2 rounded-xl border-destructive/20 hover:bg-destructive/10 text-destructive w-full md:w-auto"
              >
                {isLoading ? 'Analyzing...' : 'Analyze anyway (Not Recommended)'}
              </Button>
            )}
          </div>
        </div>
      ) : (
        <>
          <div className="flex items-center justify-between mb-6">
            <h2 className="flex items-center gap-3 text-2xl font-bold text-primary">
              <Brain className="w-8 h-8" />
              AI Portfolio Insights
            </h2>
            {!result.wasForceAnalyzed && (
              <Button variant="outline" className="gap-2 rounded-xl" onClick={generatePDF}>
                <Download className="w-4 h-4" />
                Download PDF
              </Button>
            )}
          </div>

          <Accordion type="multiple" defaultValue={["assessment", "strengths", "improvements", "content"]} className="space-y-4">
            {/* Overall Assessment */}
            <AccordionItem value="assessment" className="border border-border rounded-xl px-5">
              <AccordionTrigger className="hover:no-underline py-5">
                <span className="flex items-center gap-3 text-lg font-semibold text-secondary">
                  <CheckSquare className="w-5 h-5" />
                  Overall Assessment
                </span>
              </AccordionTrigger>
              <AccordionContent className="pb-5">
                <p className="text-foreground leading-relaxed">
                  {result.summary}
                </p>
              </AccordionContent>
            </AccordionItem>

            {/* Key Strengths */}
            <AccordionItem value="strengths" className="border border-border rounded-xl px-5">
              <AccordionTrigger className="hover:no-underline py-5">
                <span className="flex items-center gap-3 text-lg font-semibold text-primary">
                  <ThumbsUp className="w-5 h-5" />
                  Key Strengths
                </span>
              </AccordionTrigger>
              <AccordionContent className="pb-5">
                <ul className="space-y-3">
                  {result.fixes.length > 0 ? (
                    result.fixes.slice(0, Math.ceil(result.fixes.length / 2)).map((item, index) => {
                      const [title, ...rest] = item.split(':');
                      const content = rest.join(':');

                      return (
                        <li key={index} className="flex items-start gap-2.5 bg-primary/5 p-3 rounded-lg border border-primary/10">
                          <span className="text-primary mt-1 shrink-0">•</span>
                          <span className="text-foreground text-sm">
                            {content ? (
                              <>
                                <span className="font-bold text-primary block mb-1">{title.trim()}</span>
                                <span className="text-muted-foreground">{content.trim()}</span>
                              </>
                            ) : (
                              title
                            )}
                          </span>
                        </li>
                      );
                    })
                  ) : (
                    <>
                      <li className="flex items-start gap-2">
                        <span className="text-primary mt-1.5">•</span>
                        <span className="text-foreground">Strong combination of technical and soft skills.</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-primary mt-1.5">•</span>
                        <span className="text-foreground">Concrete examples of accomplishments in work history.</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-primary mt-1.5">•</span>
                        <span className="text-foreground">Practical projects demonstrating skills application.</span>
                      </li>
                    </>
                  )}
                </ul>
              </AccordionContent>
            </AccordionItem>

            {/* Key Areas for Improvement */}
            <AccordionItem value="improvements" className="border border-border rounded-xl px-5">
              <AccordionTrigger className="hover:no-underline py-5">
                <span className="flex items-center gap-3 text-lg font-semibold text-warning">
                  <AlertTriangle className="w-5 h-5" />
                  Key Areas for Improvement
                </span>
              </AccordionTrigger>
              <AccordionContent className="pb-5">
                <ul className="space-y-3">
                  {result.rejectionReasons.map((reason, index) => {
                    const [title, ...rest] = reason.split(':');
                    const content = rest.join(':');

                    return (
                      <li key={index} className="flex items-start gap-2.5 bg-warning/5 p-3 rounded-lg border border-warning/10">
                        <span className="text-warning mt-1 shrink-0">•</span>
                        <span className="text-foreground text-sm">
                          {content ? (
                            <>
                              <span className="font-bold text-foreground block mb-1">{title.trim()}</span>
                              <span className="text-muted-foreground">{content.trim()}</span>
                            </>
                          ) : (
                            title
                          )}
                        </span>
                      </li>
                    );
                  })}
                </ul>
              </AccordionContent>
            </AccordionItem>

            {/* Content Review - Hidden when force analyzed */}
            {!result.wasForceAnalyzed && (
              <AccordionItem value="content" className="border border-border rounded-xl px-5">
                <AccordionTrigger className="hover:no-underline py-5">
                  <span className="flex items-center gap-3 text-lg font-semibold text-primary">
                    <FileText className="w-5 h-5" />
                    Content Review
                  </span>
                </AccordionTrigger>
                <AccordionContent className="pb-5 space-y-6">
                  <div className="flex items-center justify-between">
                    <span className="font-semibold text-foreground">Rating:</span>
                    <StarRating rating={rating} />
                  </div>

                  <div className="border-t border-border pt-4">
                    <h4 className="font-semibold text-success mb-3">What's Strong:</h4>
                    <ul className="space-y-2">
                      <li className="flex items-start gap-2">
                        <span className="text-success mt-1.5">•</span>
                        <span className="text-foreground">The resume effectively showcases a blend of technical and soft skills, providing a well-rounded picture of your capabilities.</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-success mt-1.5">•</span>
                        <span className="text-foreground">The work history provides concrete examples of your accomplishments.</span>
                      </li>
                    </ul>
                  </div>

                  <div className="border-t border-border pt-4">
                    <h4 className="font-semibold text-warning mb-3">What to Improve:</h4>
                    <ul className="space-y-2">
                      {result.rejectionReasons.slice(0, 3).map((reason, index) => (
                        <li key={index} className="flex items-start gap-2">
                          <span className="text-warning mt-1.5">•</span>
                          <span className="text-foreground">{reason}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </AccordionContent>
              </AccordionItem>
            )}
          </Accordion>
        </>
      )}
    </div>
  );
};

export default AnalysisResult;
